[workspace]
members = ["macro"]

[workspace.package]
edition = "2024"
version = "0.2.3"
repository = "https://github.com/wdjcodes/uncollate"
authors = ["wdjcodes"]
license = "MIT"

[package]
name = "uncollate"
description = "Uncollate array of structs into arrays of field"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
path = "./src/lib.rs"

[dependencies]
uncollate_macro = { version = "0.2.2", path = "macro" }
