[workspace]
release_always = false
git_release_enable = false

[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^chore", skip = true},
    { message = "^.*", group = "other" },
]